source("activity_code_1_3.r")
#source("C:/Users/rowcliffe.m/Documents/MISC/R Scripts/density2.r")
n<-400
tt <- runif(n, 0, 2*pi)
tt <- runif(n, pi/2, pi*3/2)
tt <- runif(n, -pi/2, pi/2)
tt[tt<0] <- tt[tt<0]+2*pi

nmod <- fitact(tt)
dmod <- fitact(tt, sample="data", reps=99)
mmod <- fitact(tt, sample="model", reps=99)

dnbmod <- fitact(tt, bounds=c(6, 18)*pi/12)
ddbmod <- fitact(tt, sample="data", bounds=c(6,18)*pi/12, reps=99)
dmbmod <- fitact(tt, sample="model", bounds=c(6,18)*pi/12, reps=99)

nnbmod <- fitact(tt, bounds=c(18,6)*pi/12)
ndbmod <- fitact(tt, sample="data", bounds=c(18,6)*pi/12, reps=99)
nmbmod <- fitact(tt, sample="model", bounds=c(18,6)*pi/12, reps=99)

par(mfrow=c(3,2))
plot(nmod)
plot(nmod, centre="night")
plot(dnbmod)
plot(dnbmod, centre="night")
plot(nnbmod)
plot(nnbmod, centre="night")

plot(dmod, main="data")
plot(mmod, main="model")
plot(ddbmod)
plot(dmbmod)
plot(ndbmod)
plot(nmbmod)

plot(nmod, xunit="clock", yunit="frequency", data="histogram", centre="day", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="histogram", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="histogram", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="histogram", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="histogram", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="histogram", centre="day", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="rug", centre="day", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="rug", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="rug", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="rug", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="rug", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="rug", centre="day", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="both", centre="day", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="both", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="both", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="both", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="both", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="both", centre="day", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="none", centre="day", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="none", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="none", centre="day", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="none", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="none", centre="day", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="none", centre="day", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="histogram", centre="night", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="histogram", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="histogram", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="histogram", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="histogram", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="histogram", centre="night", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="rug", centre="night", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="rug", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="rug", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="rug", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="rug", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="rug", centre="night", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="both", centre="night", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="both", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="both", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="both", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="both", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="both", centre="night", xaxis = NULL)

plot(nmod, xunit="clock", yunit="frequency", data="none", centre="night", xaxis = NULL)
plot(nmod, xunit="clock", yunit="density", data="none", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="frequency", data="none", centre="night", xaxis = NULL)
plot(nmod, xunit="hours", yunit="density", data="none", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="frequency", data="none", centre="night", xaxis = NULL)
plot(nmod, xunit="radians", yunit="density", data="none", centre="night", xaxis = NULL)

par(mfrow=c(3,1))
plot(nmod, xaxis=list(at=seq(0,24,2), labels=seq(0,24,2)), las=1)
plot(nmod, xaxis=list(at=seq(0,24,6), labels=seq(0,24,6)), las=1)
plot(dmod, dline=list(col="grey"), tline=list(col="red", lwd=2), cline=list(col="red"))


n<-400
ttt <- seq(0, 2*pi, len=24*3600)
ww <- ifelse(ttt>pi/2 & ttt<pi*3/2, 1, 4)
tt <- sample(ttt, n, replace=T, prob=1/ww)
w <- ifelse(tt>pi/2 & tt<pi*3/2, 1, 4)
mod <- fitact(tt, reps=99, sample="data")
wmod <- fitact(tt, w, 99, sample="data")
par(mfrow=c(2,1))
plot(mod)
plot(wmod)

ttt <- seq(pi/2, pi*3/2, len=24*3600)
ww <- ifelse(ttt>pi*3/4 & ttt<pi*5/4, 1, 4)
tt <- sample(ttt, n, replace=T, prob=1/ww)
w <- ifelse(tt>pi*3/4 & tt<pi*5/4, 1, 4)
mod <- fitact(tt, reps=99, sample="data", bounds=c(pi/2, pi*3/2))
wmod <- fitact(tt, w, 99, sample="data", bounds=c(pi/2, pi*3/2))
par(mfrow=c(2,1))
plot(mod)
plot(wmod)
